"""Fix typo

Revision ID: 046a5fb51590
Revises: cb309d12a0cc
Create Date: 2024-10-06 12:53:42.570544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046a5fb51590'
down_revision = 'cb309d12a0cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('national_indicators', sa.Column('predicted_error', sa.Float(), nullable=True))
    op.drop_column('national_indicators', 'predicted_errror')
    op.add_column('subnational_indicators', sa.Column('predicted_error', sa.Float(), nullable=True))
    op.drop_column('subnational_indicators', 'predicted_errror')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subnational_indicators', sa.Column('predicted_errror', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('subnational_indicators', 'predicted_error')
    op.add_column('national_indicators', sa.Column('predicted_errror', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('national_indicators', 'predicted_error')
    # ### end Alembic commands ###
