"""remove country field

Revision ID: 0812bd5c7c9d
Revises: ab540a291236
Create Date: 2025-04-13 15:10:17.002352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0812bd5c7c9d'
down_revision = 'ab540a291236'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoint_logs', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoint_logs', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
