"""Add indices to models

Revision ID: 8735b8946bfe
Revises: 8943292cbd14
Create Date: 2025-01-11 10:33:55.397861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8735b8946bfe'
down_revision = '8943292cbd14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_indicator_descriptions_id'), 'indicator_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_national_ground_truth_gid_0'), 'national_ground_truth', ['gid_0'], unique=False)
    op.create_index(op.f('ix_national_ground_truth_outcome'), 'national_ground_truth', ['outcome'], unique=False)
    op.create_index(op.f('ix_national_ground_truth_source'), 'national_ground_truth', ['source'], unique=False)
    op.create_index(op.f('ix_national_ground_truth_survey_year'), 'national_ground_truth', ['survey_year'], unique=False)
    op.create_index(op.f('ix_national_indicators_country'), 'national_indicators', ['country'], unique=False)
    op.create_index(op.f('ix_national_indicators_date'), 'national_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_national_indicators_gid_0'), 'national_indicators', ['gid_0'], unique=False)
    op.create_index(op.f('ix_national_indicators_outcome'), 'national_indicators', ['outcome'], unique=False)
    op.create_index(op.f('ix_subnational_ground_truth_gid_0'), 'subnational_ground_truth', ['gid_0'], unique=False)
    op.create_index(op.f('ix_subnational_ground_truth_gid_1'), 'subnational_ground_truth', ['gid_1'], unique=False)
    op.create_index(op.f('ix_subnational_ground_truth_outcome'), 'subnational_ground_truth', ['outcome'], unique=False)
    op.create_index(op.f('ix_subnational_ground_truth_source'), 'subnational_ground_truth', ['source'], unique=False)
    op.create_index(op.f('ix_subnational_ground_truth_survey_year'), 'subnational_ground_truth', ['survey_year'], unique=False)
    op.create_index(op.f('ix_subnational_indicators_country'), 'subnational_indicators', ['country'], unique=False)
    op.create_index(op.f('ix_subnational_indicators_date'), 'subnational_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_subnational_indicators_gid_0'), 'subnational_indicators', ['gid_0'], unique=False)
    op.create_index(op.f('ix_subnational_indicators_gid_1'), 'subnational_indicators', ['gid_1'], unique=False)
    op.create_index(op.f('ix_subnational_indicators_outcome'), 'subnational_indicators', ['outcome'], unique=False)
    op.create_index(op.f('ix_subnational_names_country'), 'subnational_names', ['country'], unique=False)
    op.create_index(op.f('ix_subnational_names_gid_1'), 'subnational_names', ['gid_1'], unique=False)
    op.create_index(op.f('ix_subnational_names_name_1'), 'subnational_names', ['name_1'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subnational_names_name_1'), table_name='subnational_names')
    op.drop_index(op.f('ix_subnational_names_gid_1'), table_name='subnational_names')
    op.drop_index(op.f('ix_subnational_names_country'), table_name='subnational_names')
    op.drop_index(op.f('ix_subnational_indicators_outcome'), table_name='subnational_indicators')
    op.drop_index(op.f('ix_subnational_indicators_gid_1'), table_name='subnational_indicators')
    op.drop_index(op.f('ix_subnational_indicators_gid_0'), table_name='subnational_indicators')
    op.drop_index(op.f('ix_subnational_indicators_date'), table_name='subnational_indicators')
    op.drop_index(op.f('ix_subnational_indicators_country'), table_name='subnational_indicators')
    op.drop_index(op.f('ix_subnational_ground_truth_survey_year'), table_name='subnational_ground_truth')
    op.drop_index(op.f('ix_subnational_ground_truth_source'), table_name='subnational_ground_truth')
    op.drop_index(op.f('ix_subnational_ground_truth_outcome'), table_name='subnational_ground_truth')
    op.drop_index(op.f('ix_subnational_ground_truth_gid_1'), table_name='subnational_ground_truth')
    op.drop_index(op.f('ix_subnational_ground_truth_gid_0'), table_name='subnational_ground_truth')
    op.drop_index(op.f('ix_national_indicators_outcome'), table_name='national_indicators')
    op.drop_index(op.f('ix_national_indicators_gid_0'), table_name='national_indicators')
    op.drop_index(op.f('ix_national_indicators_date'), table_name='national_indicators')
    op.drop_index(op.f('ix_national_indicators_country'), table_name='national_indicators')
    op.drop_index(op.f('ix_national_ground_truth_survey_year'), table_name='national_ground_truth')
    op.drop_index(op.f('ix_national_ground_truth_source'), table_name='national_ground_truth')
    op.drop_index(op.f('ix_national_ground_truth_outcome'), table_name='national_ground_truth')
    op.drop_index(op.f('ix_national_ground_truth_gid_0'), table_name='national_ground_truth')
    op.drop_index(op.f('ix_indicator_descriptions_id'), table_name='indicator_descriptions')
    # ### end Alembic commands ###
