"""Add delete to users enum

Revision ID: 8943292cbd14
Revises: 046a5fb51590
Create Date: 2024-10-23 18:28:59.893062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8943292cbd14'
down_revision = '046a5fb51590'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userroleenum ADD VALUE 'DELETE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userroleenum RENAME TO userroleenum_old")
    op.execute("CREATE TYPE userroleenum AS ENUM('READ', 'WRITE', 'ADMIN')")
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE userroleenum
        USING role::text::userroleenum
    """)
    op.execute("DROP TYPE userroleenum_old")
