"""Fix model

Revision ID: 8ee486249cc2
Revises: 0812bd5c7c9d
Create Date: 2025-04-13 15:45:23.778872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ee486249cc2'
down_revision = '0812bd5c7c9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('endpoint_logs', 'method',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('endpoint_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('endpoint_logs', 'method',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('endpoint_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
