"""Add logs table

Revision ID: ab540a291236
Revises: 8735b8946bfe
Create Date: 2025-04-13 14:56:13.585231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab540a291236'
down_revision = '8735b8946bfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashed_ip', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('table_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_logs_id'), 'endpoint_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_logs_id'), table_name='endpoint_logs')
    op.drop_table('endpoint_logs')
    # ### end Alembic commands ###
