"""Initial migration

Revision ID: cb309d12a0cc
Revises: 
Create Date: 2024-09-29 13:52:51.192182

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

import app


# revision identifiers, used by Alembic.
revision = 'cb309d12a0cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_type', sa.String(), nullable=False),
    sa.Column('mobile_women_description', sa.String(length=255), nullable=False),
    sa.Column('mobile_women_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_men_description', sa.String(length=255), nullable=False),
    sa.Column('mobile_men_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_gender_gap_description', sa.String(length=255), nullable=False),
    sa.Column('mobile_gender_gap_name', sa.String(length=255), nullable=False),
    sa.Column('internet_women_description', sa.String(length=255), nullable=False),
    sa.Column('internet_women_name', sa.String(length=255), nullable=False),
    sa.Column('internet_men_description', sa.String(length=255), nullable=False),
    sa.Column('internet_men_name', sa.String(length=255), nullable=False),
    sa.Column('internet_gender_gap_description', sa.String(length=255), nullable=False),
    sa.Column('internet_gender_gap_name', sa.String(length=255), nullable=False),
    sa.Column('data_frequency', sa.String(length=255), nullable=False),
    sa.Column('geographical_coverage', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('national_geometries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_national_geometries_geom', 'national_geometries', ['geom'], unique=False, postgresql_using='gist')
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'idx_national_geometries_geom') THEN
            CREATE INDEX idx_national_geometries_geom ON national_geometries USING gist (geom);
        END IF;
    END
    $$;
    """)
    op.create_table('national_ground_truth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=255), nullable=False),
    sa.Column('observed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('national_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=255), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=True),
    sa.Column('predicted_errror', sa.Float(), nullable=True),
    sa.Column('date', app.models.YearMonthType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subnational_geometries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('gid_1', sa.String(length=255), nullable=False),
    sa.Column('name_1', sa.String(length=255), nullable=False),
    sa.Column('is_subnational', sa.Boolean(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_subnational_geometries_geom', 'subnational_geometries', ['geom'], unique=False, postgresql_using='gist')
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'idx_subnational_geometries_geom') THEN
            CREATE INDEX idx_subnational_geometries_geom ON subnational_geometries USING gist (geom);
        END IF;
    END
    $$;
    """)
    op.create_table('subnational_ground_truth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid_1', sa.String(length=255), nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('survey_year', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=255), nullable=False),
    sa.Column('observed', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subnational_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('gid_1', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=255), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=True),
    sa.Column('predicted_errror', sa.Float(), nullable=True),
    sa.Column('date', app.models.YearMonthType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subnational_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid_0', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('gid_1', sa.String(length=255), nullable=False),
    sa.Column('name_1', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('READ', 'WRITE', 'ADMIN', name='userroleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('subnational_names')
    op.drop_table('subnational_indicators')
    op.drop_table('subnational_ground_truth')
    op.drop_index('idx_subnational_geometries_geom', table_name='subnational_geometries', postgresql_using='gist')
    op.drop_table('subnational_geometries')
    op.drop_table('national_indicators')
    op.drop_table('national_ground_truth')
    op.drop_index('idx_national_geometries_geom', table_name='national_geometries', postgresql_using='gist')
    op.drop_table('national_geometries')
    op.drop_table('indicator_descriptions')
    # ### end Alembic commands ###
