events {
    # You can leave this block empty if you don't need specific settings
}


http {
    include /etc/nginx/mime.types;  # Include standard MIME types
    default_type application/octet-stream;
    
    include /etc/nginx/conf.d/*.conf;  # Includes all per-site configs

    gzip on;                           # Enable gzip compression
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1024;              # Only compress responses larger than 1KB
    gzip_proxied any;                  # Compress responses even for proxied requests
    gzip_comp_level 6;                 # Compression level (1=fastest, 9=best compression)
    gzip_buffers 16 8k;                # Buffers for gzip compression
    gzip_http_version 1.1;             # Use gzip for HTTP/1.1 clients
}