name: Run k6 Stress Tests

on:
  push:
    branches:
      - "*"

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t stress-k6 ./api/tests/stress

    - name: Run k6 tests
      run: docker run --rm stress-k6 run /api/tests/stress/k6-script.js
